{{ config(materialized='view') }}

WITH PAYMENT_DATA_TRANSFORMATION AS (
    SELECT
        PAYMENT_ID,
        CURRENCY_CODE,
        CUSTOMER_DETAILS,

        PARSE_JSON(REPLACE(REPLACE(CUSTOMER_DETAILS, '''', '"'),'None','null')):customer_id::STRING AS CUSTOMER_ID,
        PARSE_JSON(REPLACE(REPLACE(CUSTOMER_DETAILS, '''', '"'),'None','null')):phone_number::NUMBER AS CUSTOMER_PHONE,
        PARSE_JSON(REPLACE(REPLACE(CUSTOMER_DETAILS, '''', '"'),'None','null')):email_address::STRING AS CUSTOMER_EMAIL,
        PARSE_JSON(REPLACE(REPLACE(CUSTOMER_DETAILS, '''', '"'),'None','null')):billing_address::STRING AS CUSTOMER_BILLING_ADDRESS,

        PARSE_JSON(CUSTOMER_BILLING_ADDRESS):first_name::STRING AS CUSTOMER_FIRST_NAME,
        PARSE_JSON(CUSTOMER_BILLING_ADDRESS):last_name::STRING AS CUSTOMER_LAST_NAME,

        PARSE_JSON(CUSTOMER_BILLING_ADDRESS):address_line_1::STRING AS BILLING_STREET,
        PARSE_JSON(CUSTOMER_BILLING_ADDRESS):address_line_2::STRING AS BILLING_ADDITIONAL_ADDRESS,
        PARSE_JSON(CUSTOMER_BILLING_ADDRESS):city::STRING AS BILLING_CITY,
        PARSE_JSON(CUSTOMER_BILLING_ADDRESS):postal_code::STRING AS BILLING_POSTAL_CODE,
        PARSE_JSON(CUSTOMER_BILLING_ADDRESS):state::STRING AS BILLING_STATE,
        PARSE_JSON(CUSTOMER_BILLING_ADDRESS):country_code::STRING AS BILLING_COUNTRY_CODE,

        PARSE_JSON(REPLACE(REPLACE(CUSTOMER_DETAILS, '''', '"'),'None','null')):shipping_address::STRING AS CUSTOMER_SHIPPING_ADDRESS,
        PARSE_JSON(CUSTOMER_SHIPPING_ADDRESS):address_line_1::STRING AS SHIPPING_STREET,
        PARSE_JSON(CUSTOMER_SHIPPING_ADDRESS):address_line_2::STRING AS SHIPPING_ADDITIONAL_ADDRESS,
        PARSE_JSON(CUSTOMER_SHIPPING_ADDRESS):city::STRING AS SHIPPING_CITY,
        PARSE_JSON(CUSTOMER_SHIPPING_ADDRESS):postal_code::STRING AS SHIPPING_POSTAL_CODE,
        PARSE_JSON(CUSTOMER_SHIPPING_ADDRESS):state::STRING AS SHIPPING_STATE,
        PARSE_JSON(CUSTOMER_SHIPPING_ADDRESS):country_code::STRING AS SHIPPING_COUNTRY_CODE,

        STATEMENT_DESCRIPTOR,
        CREATED_AT::TIMESTAMP_NTZ(9) AS CREATED_AT,
        UPDATED_AT::TIMESTAMP_NTZ(9) AS UPDATED_AT,
        TOKEN_ID,
        VAULTED_TOKEN_ID,
        MERCHANT_PAYMENT_ID,
        PRIMER_ACCOUNT_ID,
        AMOUNT,
        STATUS,
        PROCESSOR_MERCHANT_ID,
        PROCESSOR,
        AMOUNT_CAPTURED,
        AMOUNT_AUTHORIZED,
        AMOUNT_REFUNDED
    FROM
        {{ source('AUTO1_PROJECT', 'PAYMENT_DATA') }}
),

PAYMENT_DATA_CLEANED AS (
    SELECT
        PAYMENT_ID,
        CURRENCY_CODE,
        CUSTOMER_DETAILS,
        CUSTOMER_ID,
        CONCAT(CUSTOMER_FIRST_NAME, ' ', CUSTOMER_LAST_NAME) AS CUSTOMER_NAME,
        CUSTOMER_PHONE,
        CUSTOMER_EMAIL,
        CASE
            WHEN BILLING_STREET IS NULL OR BILLING_CITY IS NULL THEN NULL
            ELSE
                CONCAT(
                    COALESCE(BILLING_STREET, ''), ', ',
                    COALESCE(BILLING_CITY, ''), ', ',
                    COALESCE(BILLING_POSTAL_CODE, ''), ', ',
                    COALESCE(BILLING_COUNTRY_CODE, '')
                )
        END AS CUSTOMER_BILLING_ADDRESS,
        CASE
            WHEN SHIPPING_STREET IS NULL OR SHIPPING_CITY IS NULL THEN NULL
            ELSE
                CONCAT(
                    COALESCE(SHIPPING_STREET, ''), ', ',
                    COALESCE(SHIPPING_CITY, ''), ', ',
                    COALESCE(SHIPPING_POSTAL_CODE, ''), ', ',
                    COALESCE(SHIPPING_COUNTRY_CODE, '')
                )
        END AS CUSTOMER_SHIPPING_ADDRESS,
        STATEMENT_DESCRIPTOR,
        CREATED_AT,
        UPDATED_AT,
        TOKEN_ID,
        VAULTED_TOKEN_ID,
        MERCHANT_PAYMENT_ID,
        PRIMER_ACCOUNT_ID,
        AMOUNT,
        STATUS,
        PROCESSOR_MERCHANT_ID,
        PROCESSOR,
        AMOUNT_CAPTURED,
        AMOUNT_AUTHORIZED,
        AMOUNT_REFUNDED
    FROM PAYMENT_DATA_TRANSFORMATION
)

SELECT * FROM PAYMENT_DATA_CLEANED
